# Generated by Django 4.1.1 on 2022-10-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('build_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('builders', models.ManyToManyField(to='main_app.builder')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Building Date')),
                ('rating', models.CharField(choices=[('1', 'Not Fun'), ('2', 'Kinda Fun'), ('3', 'Very Fun')], default='2', max_length=1)),
                ('lego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lego')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
